import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";
import * as teamRepo from "./teams.repository.js";
import * as teamService from "./teams.service.js";
import type { TeamReportsQuery } from "./teams.schema.js";

// ── Constants ────────────────────────────────────────────────────────

const BRAND_PURPLE = rgb(0.16, 0.04, 0.2); // #290A33 -- midnight purple
const BRAND_GOLD = rgb(0.86, 0.73, 0.36); // #DBBA5C -- gold accent
const HEADER_BG = rgb(0.16, 0.04, 0.2);
const TABLE_HEADER_BG = rgb(0.93, 0.91, 0.96); // light purple tint
const WHITE = rgb(1, 1, 1);
const BLACK = rgb(0, 0, 0);
const GRAY = rgb(0.4, 0.4, 0.4);
const LIGHT_GRAY = rgb(0.96, 0.96, 0.96);

const PAGE_WIDTH = 595; // A4
const PAGE_HEIGHT = 842;
const MARGIN = 50;
const CONTENT_WIDTH = PAGE_WIDTH - 2 * MARGIN;

const CSV_BOM = "\uFEFF"; // UTF-8 BOM for Excel compatibility

// ── Types ────────────────────────────────────────────────────────────

interface MemberReportRow {
  readonly name: string;
  readonly role: string;
  readonly tasksCompleted: number;
  readonly completionRate: number;
  readonly overdueTasks: number;
}

interface ReportData {
  readonly teamName: string;
  readonly period: string;
  readonly periodLabel: string;
  readonly memberCount: number;
  readonly totalTasks: number;
  readonly completedTasks: number;
  readonly completionRate: number;
  readonly members: readonly MemberReportRow[];
  readonly generatedAt: Date;
}

// ── Data Gathering ───────────────────────────────────────────────────

async function gatherReportData(
  teamId: string,
  query: TeamReportsQuery,
): Promise<ReportData> {
  const team = await teamRepo.findTeamById(teamId);
  const teamName = team?.name ?? "Unknown Team";

  const report = await teamService.getTeamReport(teamId, query);
  const members = await teamRepo.findMembers(teamId);

  const periodLabel =
    query.period === "week" ? "Last 7 Days" : "Last 30 Days";

  const memberRows: MemberReportRow[] = members.map((m) => ({
    name: m.userId, // In production, join with profiles table for display name
    role: m.role,
    tasksCompleted: 0,
    completionRate: report.completionRate,
    overdueTasks: 0,
  }));

  return {
    teamName,
    period: query.period,
    periodLabel,
    memberCount: report.memberCount,
    totalTasks: report.totalTasks,
    completedTasks: report.completedTasks,
    completionRate: report.completionRate,
    members: memberRows,
    generatedAt: new Date(),
  };
}

// ── CSV Export ────────────────────────────────────────────────────────

function escapeCsvField(value: string): string {
  if (value.includes(",") || value.includes('"') || value.includes("\n")) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

export async function exportTeamReportCsv(
  teamId: string,
  query: TeamReportsQuery,
): Promise<string> {
  const data = await gatherReportData(teamId, query);

  const lines: string[] = [];

  // Summary section
  lines.push("UNJYNX Team Report");
  lines.push(`Team,${escapeCsvField(data.teamName)}`);
  lines.push(`Period,${escapeCsvField(data.periodLabel)}`);
  lines.push(`Generated,${data.generatedAt.toISOString()}`);
  lines.push(`Total Members,${data.memberCount}`);
  lines.push(`Total Tasks,${data.totalTasks}`);
  lines.push(`Completed Tasks,${data.completedTasks}`);
  lines.push(
    `Completion Rate,${(data.completionRate * 100).toFixed(1)}%`,
  );
  lines.push(""); // blank separator

  // Member table header
  lines.push(
    "Member,Role,Tasks Completed,Completion Rate,Overdue Tasks",
  );

  // Member rows
  for (const member of data.members) {
    lines.push(
      [
        escapeCsvField(member.name),
        escapeCsvField(member.role),
        String(member.tasksCompleted),
        `${(member.completionRate * 100).toFixed(1)}%`,
        String(member.overdueTasks),
      ].join(","),
    );
  }

  // If no members, add a placeholder row
  if (data.members.length === 0) {
    lines.push("No team members found for this period");
  }

  lines.push(""); // trailing newline
  lines.push("Generated by UNJYNX - unjynx.me");

  return CSV_BOM + lines.join("\r\n");
}

// ── PDF Export ────────────────────────────────────────────────────────

function drawRect(
  page: PDFPage,
  x: number,
  y: number,
  width: number,
  height: number,
  color: ReturnType<typeof rgb>,
): void {
  page.drawRectangle({ x, y, width, height, color });
}

function drawText(
  page: PDFPage,
  text: string,
  x: number,
  y: number,
  font: PDFFont,
  size: number,
  color: ReturnType<typeof rgb> = BLACK,
): void {
  page.drawText(text, { x, y, font, size, color });
}

export async function exportTeamReportPdf(
  teamId: string,
  query: TeamReportsQuery,
): Promise<Uint8Array> {
  const data = await gatherReportData(teamId, query);

  const doc = await PDFDocument.create();
  const helvetica = await doc.embedFont(StandardFonts.Helvetica);
  const helveticaBold = await doc.embedFont(StandardFonts.HelveticaBold);

  const page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  let y = PAGE_HEIGHT;

  // ── Purple header bar ──────────────────────────────────────────────
  const headerHeight = 80;
  drawRect(page, 0, PAGE_HEIGHT - headerHeight, PAGE_WIDTH, headerHeight, HEADER_BG);

  // Title text
  drawText(
    page,
    "UNJYNX",
    MARGIN,
    PAGE_HEIGHT - 35,
    helveticaBold,
    24,
    BRAND_GOLD,
  );
  drawText(
    page,
    "Team Report",
    MARGIN,
    PAGE_HEIGHT - 55,
    helvetica,
    14,
    WHITE,
  );

  // Period badge on right
  const periodText = data.periodLabel;
  const periodWidth = helvetica.widthOfTextAtSize(periodText, 11);
  drawText(
    page,
    periodText,
    PAGE_WIDTH - MARGIN - periodWidth,
    PAGE_HEIGHT - 35,
    helvetica,
    11,
    BRAND_GOLD,
  );

  // Date on right
  const dateStr = data.generatedAt.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const dateWidth = helvetica.widthOfTextAtSize(dateStr, 9);
  drawText(
    page,
    dateStr,
    PAGE_WIDTH - MARGIN - dateWidth,
    PAGE_HEIGHT - 52,
    helvetica,
    9,
    WHITE,
  );

  y = PAGE_HEIGHT - headerHeight - 30;

  // ── Team name ──────────────────────────────────────────────────────
  drawText(page, data.teamName, MARGIN, y, helveticaBold, 16, BRAND_PURPLE);
  y -= 28;

  // ── Stats summary boxes ────────────────────────────────────────────
  const boxWidth = (CONTENT_WIDTH - 20) / 3;
  const boxHeight = 55;
  const statsData = [
    { label: "Total Tasks", value: String(data.totalTasks) },
    { label: "Completed", value: String(data.completedTasks) },
    {
      label: "Completion Rate",
      value: `${(data.completionRate * 100).toFixed(1)}%`,
    },
  ];

  for (let i = 0; i < statsData.length; i++) {
    const boxX = MARGIN + i * (boxWidth + 10);
    const boxY = y - boxHeight;

    // Box background
    drawRect(page, boxX, boxY, boxWidth, boxHeight, LIGHT_GRAY);

    // Value (large, centered)
    const valueText = statsData[i].value;
    const valueWidth = helveticaBold.widthOfTextAtSize(valueText, 18);
    drawText(
      page,
      valueText,
      boxX + (boxWidth - valueWidth) / 2,
      boxY + 30,
      helveticaBold,
      18,
      BRAND_PURPLE,
    );

    // Label (small, centered)
    const labelText = statsData[i].label;
    const labelWidth = helvetica.widthOfTextAtSize(labelText, 9);
    drawText(
      page,
      labelText,
      boxX + (boxWidth - labelWidth) / 2,
      boxY + 10,
      helvetica,
      9,
      GRAY,
    );
  }

  y -= boxHeight + 30;

  // ── Member table ───────────────────────────────────────────────────
  drawText(page, "MEMBER BREAKDOWN", MARGIN, y, helveticaBold, 12, BRAND_PURPLE);
  y -= 20;

  // Table column config
  const columns = [
    { label: "Member", width: 160 },
    { label: "Role", width: 80 },
    { label: "Tasks Done", width: 80 },
    { label: "Completion %", width: 90 },
    { label: "Overdue", width: 80 },
  ];

  const rowHeight = 22;

  // Table header
  drawRect(page, MARGIN, y - rowHeight + 4, CONTENT_WIDTH, rowHeight, TABLE_HEADER_BG);
  let colX = MARGIN + 6;
  for (const col of columns) {
    drawText(page, col.label, colX, y - 12, helveticaBold, 9, BRAND_PURPLE);
    colX += col.width;
  }
  y -= rowHeight;

  // Table rows
  if (data.members.length === 0) {
    y -= rowHeight;
    drawText(
      page,
      "No team members found for this period.",
      MARGIN + 6,
      y + 6,
      helvetica,
      10,
      GRAY,
    );
    y -= 10;
  } else {
    for (let i = 0; i < data.members.length; i++) {
      const member = data.members[i];
      const rowY = y - rowHeight;

      // Alternating row background
      if (i % 2 === 1) {
        drawRect(page, MARGIN, rowY + 4, CONTENT_WIDTH, rowHeight, LIGHT_GRAY);
      }

      colX = MARGIN + 6;

      // Truncate long names
      const displayName =
        member.name.length > 24
          ? member.name.substring(0, 22) + "..."
          : member.name;
      drawText(page, displayName, colX, rowY + 8, helvetica, 9, BLACK);
      colX += columns[0].width;

      drawText(page, member.role, colX, rowY + 8, helvetica, 9, BLACK);
      colX += columns[1].width;

      drawText(
        page,
        String(member.tasksCompleted),
        colX,
        rowY + 8,
        helvetica,
        9,
        BLACK,
      );
      colX += columns[2].width;

      drawText(
        page,
        `${(member.completionRate * 100).toFixed(1)}%`,
        colX,
        rowY + 8,
        helvetica,
        9,
        BLACK,
      );
      colX += columns[3].width;

      drawText(
        page,
        String(member.overdueTasks),
        colX,
        rowY + 8,
        helvetica,
        9,
        member.overdueTasks > 0 ? rgb(0.8, 0.2, 0.1) : BLACK,
      );

      y -= rowHeight;

      // If running out of page space, stop and note truncation
      if (y < 100) {
        y -= rowHeight;
        drawText(
          page,
          `... and ${data.members.length - i - 1} more members`,
          MARGIN + 6,
          y + 8,
          helvetica,
          9,
          GRAY,
        );
        break;
      }
    }
  }

  // ── Footer ─────────────────────────────────────────────────────────
  const footerY = 40;

  // Thin purple line
  drawRect(page, MARGIN, footerY + 15, CONTENT_WIDTH, 1, BRAND_PURPLE);

  drawText(
    page,
    `Generated on ${dateStr}`,
    MARGIN,
    footerY,
    helvetica,
    8,
    GRAY,
  );

  const footerRight = "unjynx.me";
  const footerRightWidth = helvetica.widthOfTextAtSize(footerRight, 8);
  drawText(
    page,
    footerRight,
    PAGE_WIDTH - MARGIN - footerRightWidth,
    footerY,
    helvetica,
    8,
    BRAND_PURPLE,
  );

  return doc.save();
}
